services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /dev/input:/dev/input:rw
      - inputtino-python:/workspace
      - uv_cache:/root/.cache/uv
      - pip_cache:/root/.cache/pip
      - pre-commit_cache:/root/.cache/pre-commit
    devices:
      - /dev/uinput
    tty: true
    stdin_open: true
    command: /bin/bash
    working_dir: /workspace

volumes:
  inputtino-python:
    name: inputtino-python
  uv_cache:
  pip_cache:
  pre-commit_cache:
